# Generated by Django 5.2.12 on 2026-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('alimentation', 'Alimentation'), ('transport', 'Transport'), ('loisirs', 'Loisirs')], max_length=50)),
                ('date_depense', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
