# Generated by Django 5.2.12 on 2026-03-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_depense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='isEditing',
            field=models.BooleanField(default=False),
        ),
    ]
