# Generated by Django 5.2.12 on 2026-03-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_depense_isediting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='isEditing',
        ),
    ]
